### ISSUE TITLE
GTID 的支持

### ISSUE THREAD

**Issue by jc3wish** [brokercap/Bifrost#103]
对 GTID 的支持，解决 mysql 主从自动切换，的高可用问题

**Comment by jc3wish** [comment]
v1.7 开始已经支持

**Comment by wpepec** [comment]
![image](https://user-images.githubusercontent.com/65851778/143007295-7e5dd024-d0f5-40d8-bbf4-5533a4c9e71b.png)
大佬！！！这个怎么填写啊
