### ISSUE TITLE
安装后配置数据源的时候点提交后页面显示空白

### ISSUE THREAD

**Issue by jucilang** [brokercap/Bifrost#116]
**Version:**

 - Bifrost Version: [v1.6.2]
 - Os Version: [ CentOS Linux release 7.6.1908]
 - Browse: [Chrome]

2020/12/22 19:33:50 xgo doController: runtime error: invalid memory address or nil pointer dereference goroutine 170 [running]:
runtime/debug.Stack(0xc00072d498, 0xc02640, 0x126a130)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/brokercap/Bifrost/admin/xgo.(*routeController).DoController.func1()
	/mnt/hgfs/project/gopath/src/github.com/brokercap/Bifrost/admin/xgo/xgo.go:71 +0x78
panic(0xc02640, 0x126a130)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/brokercap/Bifrost/admin/controller.(*DBController).Detail(0xc0002005a0)
	/mnt/hgfs/project/gopath/src/github.com/brokercap/Bifrost/admin/controller/db_detail.go:26 +0x9e
reflect.Value.call(0xce4680, 0xc0002005a0, 0x2613, 0xcfc1be, 0x4, 0x0, 0x0, 0x0, 0xe0e9c0, 0xc0000316e0, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0xce4680, 0xc0002005a0, 0x2613, 0x0, 0x0, 0x0, 0xc0002005a0, 0x2613, 0xc0001a6660)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/brokercap/Bifrost/admin/xgo.(*routeController).DoController0(0xc0001a86c0, 0xdfd7a0, 0xc0001e0620, 0xc000172200)
	/mnt/hgfs/project/gopath/src/github.com/brokercap/Bifrost/admin/xgo/xgo.go:87 +0x245
github.com/brokercap/Bifrost/admin/xgo.(*routeController).DoController(0xc0001a86c0, 0xdfd7a0, 0xc0001e0620, 0xc000172200)
	/mnt/hgfs/project/gopath/src/github.com/brokercap/Bifrost/admin/xgo/xgo.go:76 +0xae
github.com/brokercap/Bifrost/admin/xgo.rounteFunc(0xdfd7a0, 0xc0001e0620, 0xc000172200)
	/mnt/hgfs/project/gopath/src/github.com/brokercap/Bifrost/admin/xgo/xgo.go:144 +0x217
net/http.HandlerFunc.ServeHTTP(0xd37cc8, 0xdfd7a0, 0xc0001e0620, 0xc000172200)
	/usr/local/go/src/net/http/server.go:2042 +0x44
net/http.(*ServeMux).ServeHTTP(0x1284d80, 0xdfd7a0, 0xc0001e0620, 0xc000172200)
	/usr/local/go/src/net/http/server.go:2417 +0x1ad
net/http.serverHandler.ServeHTTP(0xc0001e0380, 0xdfd7a0, 0xc0001e0620, 0xc000172200)
	/usr/local/go/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000114320, 0xdff360, 0xc0001a9a00)
	/usr/local/go/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2969 +0x36c

**Comment by jc3wish** [comment]
请问你是修改了配置文件里的用户名和密码吗？

`
[user]
Bifrost=Bifrost123
BifrostMonitor=Bifrost123

[groups]
#administrator 管理人员可以添加删除等操作
#monitor 只能查看数据
Bifrost=administrator
BifrostMonitor=monitor

`

假如是修改了
`
[user]
Bifrost=Bifrost123
`

请记得也修改 [groups]里对应的 用户名和组

`
[groups]
#administrator 管理人员可以添加删除等操作
#monitor 只能查看数据
Bifrost=administrator
`

**Comment by jucilang** [comment]
是的，我修改了用户名密码，我试试您说的处理方式，谢谢。
