### ISSUE TITLE
8.0.22与8.0.18偶尔binlog解析不全

### ISSUE THREAD

**Issue by tianqizhanhao1234** [brokercap/Bifrost#117]
**Version:**

 - Bifrost Version: [e.g. v1.6.2-realease]
 - Os Version: [e.g. CentOS Linux release 7.7.1908]
 - Browse: [e.g. Chrome]

**Describe the bug**
最简单的一个表，反复进行delete全表，从另外一个表插入数据
create table tab1(id integer not null,name varchar(20),primary key(id)); 
insert into tab1  select * from  bak_tab1; 
delete from tab1; 
反复执行几次，会发现偶发性的要么没有解析到Insert，要么没有解析到delete,  我设置的batchsize=1

在plugin/mysql/mysql.go的Query函数入口打断点，发现在出错时根本不会到这，所以怀疑解析有bug，请作者告知如何排查

**Comment by tianqizhanhao1234** [comment]
> 在



> 的

**Comment by jc3wish** [comment]
尝试更新到 v1.6.3 版本

v1.6.3 更新内容：
1. 修复plugin mysql 主键非自增的时候丢数据的bug
2. 修复plugin ddl 同步造成的阻塞的bug
3. 修复plugin 同步出错不报错而造成丢数据的bug
4. 修复dateime(6)类型默认值为0000-00-00 00:00:00.000000解析出错的bug
5. 流量统计优化减少对map的操作，界面流量显示优化
6. 用户登入验证Host支持多个Host配置，用逗号隔开
7. plugin clickhouse 优化对源是float类型的数据转换
8. 其他已知的部分bug修复及界面优化

**Comment by tianqizhanhao1234** [comment]
这个可以关闭了，新版本已经修复
