### ISSUE TITLE
Unknown prepared statement handler (1) given to mysqld_stmt_execute

### ISSUE THREAD

**Issue by hwy1782** [brokercap/Bifrost#142]
**Version:**

 - Bifrost Version: v1.7.4-release
 - Os Version: CentOS Linux release 7.5.1804 (Core)
 - Browse:  Chrome
 - mysql版本：MariaDB 10.1.9 (兼容Mysql 5.6)

**Describe the bug**

添加数据源报错，点击 check 按钮，报错：

![image](https://user-images.githubusercontent.com/2442046/115351930-5aef0d80-a1e9-11eb-8fc0-1c16f98096dd.png)

```
Error 1243: Unknown prepared statement handler (1) given to mysqld_stmt_execute
```

我在网上找到了一个类似的问题：
https://github.com/go-sql-driver/mysql/issues/455

**Comment by jc3wish** [comment]
docker 包里没有 10.1.9 版本


测试了 mariadb:10.1.48，  mariadb:10.0 版本 

bifrost版本：

v1.7.4-release
v1.8.0-beta.01 均没问题

没有发现问题，请提供更为详细的一些信息。或者尝试升级其他版本尝试看看
