### ISSUE TITLE
能否只允许insert操作

### ISSUE THREAD

**Issue by aloasut** [brokercap/Bifrost#152]
设想是用mysql做中间库，通过bifrost入库到clickhouse
从mysql同步到clickhouse的时候，需要定时删除mysql的数据防止数据源过大。
这样就需要bifrost忽略掉delete的操作，请问可以设置吗？

**Comment by jc3wish** [comment]
采用bf 自动建表模式,建的是 replaceMergeTree 引擎的表
源端删除操作,也会转成insert的方式写入到clickhouse, 但是 replaceMergeTree  会自动的合并数据,同一条数据,只会保留一条,并且 默认情况下,ck表中,会有一个字段,标记数据是否已被删除

**Comment by Fanduzi** [comment]
> 采用bf 自动建表模式,建的是 replaceMergeTree 引擎的表
> 源端删除操作,也会转成insert的方式写入到clickhouse, 但是 replaceMergeTree 会自动的合并数据,同一条数据,只会保留一条,并且 默认情况下,ck表中,会有一个字段,标记数据是否已被删除

请问update也是转为insert吗? 然后通过argMax处理(以一个时间列作为version)?
