### ISSUE TITLE
请教一下Biforst同步到ClickHouse的问题

### ISSUE THREAD

**Issue by Fanduzi** [brokercap/Bifrost#156]
## 1.请问对于update delete
是使用这种方式处理的吗吗 https://mp.weixin.qq.com/s/a8OfsBn9VFnj7oxp0IIVGg
ReplacingMergeTree + 视图(argMax)? + is_delete列?

## 2.全量数据拉取完成后, 咱们这边是如何知道从哪个点消费binlog做增量呢? 是类似逻辑备份的原理吗

FLUSH /*!40101 LOCAL */ TABLES 
' # 对整个实例加全局读锁，如果存在表锁将阻塞加全局读锁语句'

FLUSH TABLES WITH READ LOCK
' #在session级别修改隔离级别为RR'

SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE READ
'# 开启一个一致性快照事务，必须在隔离级别RR下才能开启一个快照事务'

START TRANSACTION /*!40100 WITH CONSISTENT SNAPSHOT */ 
'#查看是否开启GTID'

SHOW VARIABLES LIKE 'gtid\_mode' 
'#如果开启GTID则查看当前的事务GTID集合'

SELECT @@GLOBAL.GTID_EXECUTED 
'#查看当前数据的binlog pos'

SHOW MASTER STATUS  
'#释放全局读锁'

UNLOCK TABLES 

开始对指定表执行SELECT获取全量数据
FTWRL 目的获取binlog file pos 或 GTID. 开启RR级别保证后续所有表的查询结果都是在一个一致性的视图中获取
增量同步时是根据binlog file pos 还是 GTID呢?

## 3.写入clickhouse是否使用batch insert
对于OLTP数据库 DML可能是频繁地小事务, clickhouse建议batch insert, 避免too many part合并不过来, 咱们这边对源端产生的语句转换为INSERT后有做缓存然后再Batch insert写入clickhouse吗?还是就是源端来1条clickhouse就插一次
比如mysql执行1000个insert , clickhouse是执行1000个insert还是1个insert values1000个?

## 4.MySQL源端DDL
- DDL如何处理? 尤其是使用PT-OST GH-OST等类似工具时
>工具原理是创建影子表, DDL应用在影子表上, 全量增量数据同步后再和源表做切换, 那么消费binlog就不能只是消费源表的binlog还要消费影子表的binlog(至少要消费影子表的ALTER语句)

- 加索引. 加索引clickhouse会自行忽略吗

**Comment by jc3wish** [comment]
1. 自动建表 是 ReplacingMergeTree 引擎 , delete,insert, update 都转成 insert 到 clickhouse中, 没有主键的表会自动丢弃, 按主键去重,查询的时候 ,需要自行加 where binlog_event_type != 'delete'  及使用final 去重

2. 在添加数据源的时候,就已经获取到了一个位点信息, 你开启全量任务之后,待全量跑完,再点击增量开启即可

3. batch insert, batch size 在配置同步的时候 ,可以自己配置,建议采用默认值, 最好自己测试了再做决定 

4. 只有自动建表,才支持DDL,当前DDL 尽支持修改字段类型,加字段 修改表名 , 更多DDL 请测试 https://github.com/brokercap/Bifrost/pull/150  这个合并,,,对gh-ost等工具的支持程度,请自行测试


请自行查阅文档和测试

https://wiki.xbifrost.com

**Comment by Fanduzi** [comment]
> 1. 自动建表 是 ReplacingMergeTree 引擎 , delete,insert, update 都转成 insert 到 clickhouse中, 没有主键的表会自动丢弃, 按主键去重,查询的时候 ,需要自行加 where binlog_event_type != 'delete'  及使用final 去重
> 2. 在添加数据源的时候,就已经获取到了一个位点信息, 你开启全量任务之后,待全量跑完,再点击增量开启即可
> 3. batch insert, batch size 在配置同步的时候 ,可以自己配置,建议采用默认值, 最好自己测试了再做决定
> 4. 只有自动建表,才支持DDL,当前DDL 尽支持修改字段类型,加字段 修改表名 , 更多DDL 请测试 [V1.8.x #150](https://github.com/brokercap/Bifrost/pull/150)  这个合并,,,对gh-ost等工具的支持程度,请自行测试
> 
> 请自行查阅文档和测试
> 
> https://wiki.xbifrost.com

好的谢谢, 其实第二个问题是想了解下咱们这边获取增量同步位点信息的原理. 我理解是两种方:
1. mysqldump --single-transaction的逻辑, 就是我上面说的
2. 在全量select前就随便获取一个位点. 并且多个表的select也不必保证在一个一致性视图, 因为反正update delete都是insert. 最终都会通过version字段去除无用数据.

**Comment by jc3wish** [comment]
在新增数据源的时候 , 会自动获取那个时间点的位点信息, 点击数据源开启的时候 ,就增量的开启,,就是从那个位点开启的,,操作一下就知道了

**Comment by Fanduzi** [comment]
> 在新增数据源的时候 , 会自动获取那个时间点的位点信息, 点击数据源开启的时候 ,就增量的开启,,就是从那个位点开启的,,操作一下就知道了

谢谢, 看您的回复我理解这个位点不是一个严格一致性的位点 , 而是一个有`提前量`的位点
