### ISSUE TITLE
http插件使用httpBasic验证的时候出错

### ISSUE THREAD

**Issue by Allen0769** [brokercap/Bifrost#195]
- Bifrost Version:  v1.8.4-release amd64
 - Os Version: Ubuntu 20.04
 - Browse: Chrome

1.使用http-v1.6.0插件创建目标库的时候，按照例子填入带http Basic验证的url，check失败
http://192.168.64.168:8080/data-api/api/allen-studio/test/bifrost

返回错误提示框，内容如下：
Get "demo:demo123": unsupported protocol scheme "demo"

2.单独在浏览器地址栏使用
http://demo:demo123@192.168.64.168:8080/data-api/api/allen-studio/test/bifrost
能成功访问接口

3.尝试使用http://demo:demo123@192.168.64.168:8080/data-api/api/allen-studio/test/bifrost 作为ConnUri，返回提示框显示只有一个"error"

4.目标url服务去掉http验证的拦截，在bifrost使用http://192.168.64.168:8080/data-api/api/allen-studio/test/bifrost 作为ConnUri，check才能显示成功

**Comment by jc3wish** [comment]
如果 Http 需要 BasicAuth 验证

界面输入框是格式如下：

user:pwd@http://a.Bifrist.com?bifrost_api=ok ;

**Comment by Allen0769** [comment]
更正一下，目前第一步就是使用
demo:demo123@http://192.168.64.168:8080/data-api/api/allen-studio/test/bifrost
返回错误提示框，内容如下：
Get "demo:demo123": unsupported protocol scheme "demo"
