### ISSUE TITLE
MySQL同步到CK时Decimal(18, 2)字段偶尔错误

### ISSUE THREAD

**Issue by BruceMaa** [brokercap/Bifrost#204]
**Version:**

 - Bifrost Version: [v1.8.7-release]
 - Os Version: [CentOS Linux release 7.7.1908]
 - Browse: [Chrome]

**Describe the bug**

MySQL表中有Decimal(18, 2)类型字段，同步到CK时选择自动创建表（手动创建相同属性也一样），CK表中字段也是Decimal(18, 2)类型。
同步**3000**多条数据，其中有**3 至 5**条数据，小数位错误。
比如MySQL中原数据为 **149.14**，CK中对应的数据为 **149.13** 。

将相同的表同步到另一个MySQL数据库中，没有此问题。

**Screenshots**

![image](https://user-images.githubusercontent.com/12798069/195805191-6c7ef9e0-13ab-4f94-9a85-771b8eb1a309.png)

**Additional context**

查看处理Decimal类型的源码

https://github.com/brokercap/Bifrost/blob/522456abf7e1fda794290b5a554b4db154889962/plugin/clickhouse/src/transfer.go#L432-L453

是做了Float64的转换，是否可以修改为String的转换，CK支持String数据添加到Decimal类型字段中。

**Comment by jc3wish** [comment]
因为驱动包原因，需要对驱动包升级，后续版本修复
