### ISSUE TITLE
将MySQL同步到elastic Bifrost 插件

### ISSUE THREAD

**Issue by jc3wish** [brokercap/Bifrost#38]
将数据实时同步到 elastic

支持普通 模式和日志模式同步

1.普通模式
数据源里update和delete里，elastic里也相应的 update和delete操作

2. 日志模式
不管数据源里是insert, update,delete，统一是以新增的方式同步到elastic

elastic 插件需要支持自定义索引名称及对 BIfrost 标签的功能

**Comment by sj1385** [comment]
什么时候可以支持mysql binlog2es的插件
