### ISSUE TITLE
Com_stmt_close没有关闭

### ISSUE THREAD

**Issue by xieyuhua** [brokercap/Bifrost#60]
[mysqld-5.5.17-log]Can't create more than max_prepared_stmt_count statements (current value: 16382)

**Comment by xieyuhua** [comment]
mysql>  SHOW GLOBAL STATUS LIKE 'com_stmt%';
+-------------------------+-------+
| Variable_name           | Value |
+-------------------------+-------+
| Com_stmt_close          | 2412  |
| Com_stmt_execute        | 2448  |
| Com_stmt_fetch          | 0     |
| Com_stmt_prepare        | 2448  |
| Com_stmt_reprepare      | 0     |
| Com_stmt_reset          | 0     |
| Com_stmt_send_long_data | 0     |
+-------------------------+-------+
7 rows in set

**Comment by jc3wish** [comment]
> [mysqld-5.5.17-log]Can't create more than max_prepared_stmt_count statements (current value: 16382)

请问bifrost 是哪一个版本？

**Comment by xieyuhua** [comment]
版本是1.2.2。重启也没有关闭，搞不懂，
+-------------------------+---------+
| Variable_name           | Value   |
+-------------------------+---------+
| Com_stmt_execute        | 9716305 |
| Com_stmt_close          | 7603134 |
| Com_stmt_fetch          | 0       |
| Com_stmt_prepare        | 9716362 |
| Com_stmt_reset          | 0       |
| Com_stmt_send_long_data | 0       |
| Com_stmt_reprepare      | 0       |
+-------------------------+---------+

**Comment by jc3wish** [comment]
bifrost v1.4.2 版本开始修复了一下 获取 connect_id() ，stmt 句柄没有释放的 bug

可以尝试更新到 当前最新版本
