### ISSUE TITLE
跟amd64架构绑定,不支持aarch64架构

### ISSUE THREAD

**Issue by darmac** [brokercap/Bifrost#72]
build.sh中写死了编译架构. 能否通过自动识别单板架构支持aarch64呢?
```
    CGO_ENABLED=0 GOOS=$mode GOARCH=amd64 go build ./Bifrost.go
```

**Comment by jc3wish** [comment]
前几天已经修改好了编译脚本，但是当前没有 arm 机器测试
等测试好了，会进行更新，并且同时会进行提供bifrost linux/arm64 的二进制可执行包下载

**Comment by darmac** [comment]
OK, Thanks.

**Comment by jc3wish** [comment]
v1.5.0-beta.01 版本已发布
已支持 arm 的编译支持
例如：
./build.sh linux arm64

**Comment by darmac** [comment]
收到, 感谢.
