### ISSUE TITLE
nginx 配置外部域名，无法访问

### ISSUE THREAD

**Issue by kwz1993** [brokercap/Bifrost#77]
您好，请教个问题。
docker 启动之后，证书也有做相应替换。
IP+端口 是可以访问的。
配置域名之后，https访问一直失败，400错误。
请问下这是什么问题。

**Comment by jc3wish** [comment]
可以尝试 https 证书放在 nginx 层处理
bifrost 层 配置成 http 的方式
将 Bifrost.ini 配置文件中
设置
tls=false

即可

**Comment by kwz1993** [comment]
已解决，感谢。
