### ISSUE TITLE
unexpected end of JSON input

### ISSUE THREAD

**Issue by yanglanlan** [brokercap/Bifrost#9]
版本号v1.1.0-beta.06
/table/addtoserver 
出入参数：
dbname: tct
schema_name: xxx
table_name: xxx
toserver_key: mq
plugin_name: rabbitmq
mustbe: true
FilterQuery: true
FilterUpdate: true
fieldlist: xxx,xxx

输出：
{"status":false,"msg":"unexpected end of JSON input"}

**Comment by jc3wish** [comment]
请你,请问这个地方是在程序中调API的还是在界面添加的?
看参数情况下,像是没有传 参数 为 param  的参数 eg 如下:
```
dbname: myTest
schema_name: bifrost_test
table_name: binlog_field_test
toserver_key: rabbitmqTest
plugin_name: rabbitmq
mustbe: true
FilterQuery: true
FilterUpdate: true
fieldlist: 
param: {"Queue":{"Name":"testQueueName","Durable":true,"AutoDelete":false},"Exchange":{"Name":"amq.direct","Type":"direct","Durable":true,"AutoDelete":false},"Confirm":true,"Persistent":true,"RoutingKey":"testQueueNameRoutingKey","Expir":0,"Declare":true}
```
